### PR TITLE
Update Faraday to version 1.0

### PR DESCRIPTION
**Pull request by AlexWayfer**
`faraday_middleware` was updated only recently.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
@mauricew I'm going to work on my own fork, or I can help you with this repository if you want.

**Comment by AlexWayfer** [comment]
You can check a progress here: https://github.com/AlexWayfer/ruby-twitch-api/commits/fork

There just need to be done too many tasks, and I want to use this gem, so one task depends on another.

I can create a large PR later, if you agree, but it'd be difficult to separate this branch into independent small PRs.

**Comment by mauricew** [comment]
Hey, going to add you as a collaborator for this and future changes. Thanks for the help and investment in this project.

**Comment by AlexWayfer** [comment]
> Hey, going to add you as a collaborator for this and future changes. Thanks for the help and investment in this project.

Thank you! I've accepted.

One more thing: I want to connect new applications for this project, if you're not against. It's [Depfu](https://depfu.com/), [Cirrus CI](https://cirrus-ci.org/) and [Codecov](https://codecov.io/). I had a good experience with them, they're helping a lot. For example, you can see one of many (across all projects which I know) example of strange Travis CI behavior right in this PR.

**Comment by AlexWayfer** [comment]
> Yeah that's strange, it can certainly be done. Is this branch good to go?

This branch uses these 3 services. And I think it's better to enable them first, then I will create a PR from this branch, and we'll see checks in this PR, just to be sure that everything (including specs) works.

**Comment by AlexWayfer** [comment]
So, @mauricew, can you please enable these three services before a large PR with their configuration?

**Comment by mauricew** [comment]
I've got all 3 set up now.

**Comment by AlexWayfer** [comment]
> I've got all 3 set up now.

Awesome! Thanks. #18 is ready.

**Pull request merged**
