### PR TITLE
Simplify client and add ability to request raw http response

### PR DESCRIPTION
**Pull request by davehartnoll**
My main reason for making changes here is that I wanted the ability to access the raw http response just to confirm that there's no information missing (as the New Twitch API is still under development).

The best way I could see of gaining access to that raw data was to refactor the client so that more of the responsibility for constructing the response in the Response object.

To get access to raw data, add with_raw: true to the Twitch::Client.new() call.

NB: these changes against the dev branch.

### CODE REVIEW

**Comment by mauricew** [comment]
This looks useful, I'll review it soon. I do have doubts on whether to keep this permanently, but it might be for the best - I'm also considering making the raw get/post/put methods public as well for this reason..

I'll actually finalize the code for extra endpoints in the dev branch separately from this (the initialize methods for the recent data models)

**Comment by mauricew** [comment]
Ok you can go ahead and rebase/tweak the changes, I'll make it part of the upcoming release.

**Comment by davehartnoll** [comment]
OK, the pull request is now rebased upon your latest dev branch.

**Comment by mauricew** [comment]
Alright good to go.

**Pull request merged**
